"""Alert generation for Sniper V2.

Writes markdown alert files in the ``SNIPER_ALERTS.md`` / ``SNIPER_ALERTS_LLM.md``
format used by the Seoul Lab wiki.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_HEADER_TEMPLATE = """# Sniper V2 Alerts

> Generated: {timestamp}
> Platform: {platform}
> Queries: {query_count}
> New listings: {new_count}

---

"""

_TABLE_HEADER = "| # | Title | Price | Platform | URL | Timestamp |\n|---|-------|-------|----------|-----|-----------|\n"

_ROW_TEMPLATE = "| {idx} | {title} | {price} | {platform} | [Link]({url}) | {ts} |\n"


def write_alerts(
    listings: list[dict[str, Any]],
    output_path: str | Path,
    platform: str = "daangn",
    query: str = "",
) -> Path:
    """Write a markdown alert file for *listings*.

    Parameters
    ----------
    listings:
        List of listing dicts (must have ``title``, ``price`` or ``price_krw``,
        ``url``).
    output_path:
        File path to write.
    platform:
        Platform name for the table column.
    query:
        Query string used (included in header).

    Returns
    -------
    Path
        Resolved output path.
    """
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [_HEADER_TEMPLATE.format(
        timestamp=now,
        platform=platform,
        query_count=1 if query else 0,
        new_count=len(listings),
    )]

    if not listings:
        lines.append("_No new alerts this run._\n")
    else:
        lines.append(_TABLE_HEADER)
        for idx, item in enumerate(listings, 1):
            title = item.get("title") or item.get("name") or "(untitled)"
            price = item.get("price") or item.get("price_krw") or 0
            price_str = f"₩{price:,}" if price else "무료/문의"
            url = item.get("url", "#")
            ts = item.get("listed_at") or item.get("timestamp") or now
            lines.append(
                _ROW_TEMPLATE.format(
                    idx=idx,
                    title=title.replace("|", "/"),
                    price=price_str,
                    platform=platform,
                    url=url,
                    ts=ts,
                )
            )

    with p.open("w", encoding="utf-8") as f:
        f.writelines(lines)

    logger.info("Wrote %d alerts to %s", len(listings), p)
    return p


def append_alerts(
    listings: list[dict[str, Any]],
    output_path: str | Path,
    platform: str = "daangn",
) -> Path:
    """Append new alerts to an existing markdown file, or create it."""
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if p.exists():
        existing = p.read_text(encoding="utf-8")
        # Find the last table end and insert after it
        lines = existing.splitlines()
    else:
        lines = [
            f"# Sniper V2 Alerts\n\n> Auto-generated by Sniper V2\n\n",
            _TABLE_HEADER,
        ]

    for item in listings:
        title = item.get("title") or item.get("name") or "(untitled)"
        price = item.get("price") or item.get("price_krw") or 0
        price_str = f"₩{price:,}" if price else "무료/문의"
        url = item.get("url", "#")
        ts = item.get("listed_at") or item.get("timestamp") or now
        idx = len([l for l in lines if l.startswith("|") and not l.startswith("| #")])
        lines.append(
            _ROW_TEMPLATE.format(
                idx=idx,
                title=title.replace("|", "/"),
                price=price_str,
                platform=platform,
                url=url,
                ts=ts,
            )
        )

    with p.open("w", encoding="utf-8") as f:
        f.writelines(line + "\n" if not line.endswith("\n") else line for line in lines)

    return p
